version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - static_network
    restart: always
    depends_on:
      - nuxt

  nuxt:
    build: ./
    networks:
      - static_network
    restart: always
    ports:
      - "3000:3000"
    command:
      "yarn start"

networks: 
  static_network:
